# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("queued", "In Warteschlange"),
                            ("running", "Läuft"),
                            ("done", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                            ("cancelled", "Abgebrochen"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("negative_prompt", models.TextField(blank=True)),
                (
                    "reference_image",
                    models.ImageField(blank=True, upload_to="jobs/refs/"),
                ),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("num_images", models.PositiveIntegerField(default=1)),
                ("model", models.CharField(blank=True, max_length=30)),
                ("num_steps", models.PositiveIntegerField(blank=True, null=True)),
                ("guidance", models.FloatField(blank=True, null=True)),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("celery_chain_id", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PipelineTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shirt_batch", "Shirt Batch"),
                            ("poster_offset", "Poster Offset"),
                            ("card_pod", "Karte POD"),
                            ("vector_art", "Vektor Art"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("step_generate", models.BooleanField(default=True)),
                ("step_upscale", models.BooleanField(default=True)),
                ("step_vectorize", models.BooleanField(default=False)),
                ("step_cmyk", models.BooleanField(default=False)),
                ("step_pod_export", models.BooleanField(default=True)),
                ("step_preview", models.BooleanField(default=True)),
                ("step_mockup", models.BooleanField(default=False)),
                ("step_auto_qa", models.BooleanField(default=False)),
                ("default_width", models.PositiveIntegerField(default=1024)),
                ("default_height", models.PositiveIntegerField(default=1024)),
                ("default_dpi", models.PositiveIntegerField(default=300)),
                ("default_steps", models.PositiveIntegerField(default=30)),
                ("default_guidance", models.FloatField(default=7.5)),
                (
                    "default_model",
                    models.CharField(
                        choices=[
                            (
                                "flux_schnell",
                                "FLUX Schnell (Apache 2.0 — kommerziell OK)",
                            ),
                            ("flux_dev", "FLUX Dev (NICHT für Verkauf!)"),
                            ("sdxl", "SDXL (kommerziell OK)"),
                            ("custom_lora", "Custom LoRA (Lizenz prüfen!)"),
                        ],
                        default="flux_schnell",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pipeline-Template",
                "verbose_name_plural": "Pipeline-Templates",
            },
        ),
        migrations.CreateModel(
            name="PromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("category", models.CharField(max_length=60)),
                ("base_text", models.TextField()),
                ("variables", models.JSONField(default=dict)),
                (
                    "example_output",
                    models.ImageField(blank=True, upload_to="jobs/prompt_examples/"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Prompt-Template",
                "verbose_name_plural": "Prompt-Templates",
            },
        ),
        migrations.CreateModel(
            name="JobStep",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("generate", "Generierung"),
                            ("upscale", "Upscaling"),
                            ("vectorize", "Vektorisierung"),
                            ("cmyk_export", "CMYK Export"),
                            ("pod_export", "POD Export"),
                            ("preview_export", "Preview Export"),
                            ("mockup_gen", "Mockup Generierung"),
                            ("auto_qa", "Auto QA"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("running", "Läuft"),
                            ("done", "Fertig"),
                            ("skipped", "Übersprungen"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("params", models.JSONField(default=dict)),
                ("output_asset_id", models.UUIDField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_msg", models.TextField(blank=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job-Step",
                "verbose_name_plural": "Job-Steps",
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="job",
            name="pipeline_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="jobs.pipelinetemplate"
            ),
        ),
    ]
