# Generated by Django 5.1.15 on 2026-07-19 12:57

from django.db import migrations
from django.utils.text import slugify
import uuid


def create_default_project(apps, schema_editor):
    """
    Erstellt Default-Projekt "Allgemein" und weist alle bestehenden Jobs/Images zu.
    """
    Project = apps.get_model('jobs', 'Project')
    Job = apps.get_model('jobs', 'Job')
    GalleryImage = apps.get_model('gallery', 'GalleryImage')
    User = apps.get_model('auth', 'User')

    # Ersten User als Projekt-Owner verwenden (normalerweise Superuser)
    try:
        admin_user = User.objects.filter(is_superuser=True).first() or User.objects.first()
        if not admin_user:
            # Kein User vorhanden — Skip (Projekt-System noch nicht aktiv)
            return
    except Exception:
        return

    # Default-Projekt erstellen wenn noch nicht vorhanden
    default_project, created = Project.objects.get_or_create(
        slug='allgemein',
        defaults={
            'id': uuid.uuid4(),
            'title': 'Allgemein',
            'description': 'Standard-Projekt für unkategorisierte Jobs und Assets',
            'created_by': admin_user,
            'is_active': True
        }
    )

    if created:
        print(f"✅ Default-Projekt '{default_project.title}' erstellt (ID: {default_project.id})")

    # Alle Jobs ohne Projekt zuweisen
    jobs_updated = Job.objects.filter(project__isnull=True).update(project=default_project)
    print(f"✅ {jobs_updated} Jobs dem Default-Projekt zugewiesen")

    # Alle GalleryImages ohne Projekt zuweisen
    images_updated = GalleryImage.objects.filter(project__isnull=True).update(project=default_project)
    print(f"✅ {images_updated} GalleryImages dem Default-Projekt zugewiesen")


def reverse_default_project(apps, schema_editor):
    """
    Rollback: Entfernt Default-Projekt und setzt alle FKs auf NULL.
    """
    Project = apps.get_model('jobs', 'Project')
    Job = apps.get_model('jobs', 'Job')
    GalleryImage = apps.get_model('gallery', 'GalleryImage')

    # Default-Projekt finden und alle Zuordnungen entfernen
    try:
        default_project = Project.objects.get(slug='allgemein')
        Job.objects.filter(project=default_project).update(project=None)
        GalleryImage.objects.filter(project=default_project).update(project=None)
        default_project.delete()
        print("✅ Default-Projekt 'Allgemein' gelöscht, alle FKs auf NULL gesetzt")
    except Project.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_add_project_system"),
        ("gallery", "0002_add_project_system"),  # Gallery-Migration als Dependency
    ]

    operations = [
        migrations.RunPython(create_default_project, reverse_default_project),
    ]
