# Generated by Django 5.1.15 on 2026-07-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_create_default_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipelinetemplate",
            name="step_face_swap",
            field=models.BooleanField(
                default=False,
                help_text="Gesicht aus reference_image auf generiertes Bild übertragen",
            ),
        ),
    ]
