# Generated by Django 5.1.15 on 2026-07-20 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_add_face_swap_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="pipeline_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Pipeline wird nach Bildgenerierung im Produkt-Wizard zugewiesen",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="jobs.pipelinetemplate",
            ),
        ),
    ]
