# Generated by Django 4.2.30 on 2026-07-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0006_pipeline_template_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="face_image",
            field=models.ImageField(
                blank=True,
                help_text="Gesichts-Bild für Face Swap (wird auf reference_image übertragen)",
                upload_to="jobs/faces/",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                help_text="Für Img2Img (SDXL) oder Target-Bild für Face Swap",
                upload_to="jobs/refs/",
            ),
        ),
    ]
