# Generated by Django 5.1.15 on 2026-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0010_add_face_swap_step_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobstep",
            name="step_type",
            field=models.CharField(
                choices=[
                    ("generate", "Generierung"),
                    ("face_swap", "Face Swap"),
                    ("upscale", "Upscaling"),
                    ("vectorize", "Vektorisierung"),
                    ("cmyk_export", "CMYK Export"),
                    ("pod_export", "POD Export"),
                    ("preview_export", "Preview Export"),
                    ("mockup_gen", "Mockup Generierung"),
                    ("auto_qa", "Auto QA"),
                    ("quick_adjust", "Quick Adjust"),
                    ("crop", "Zuschneiden"),
                    ("notify_studio", "Studio-Benachrichtigung"),
                ],
                max_length=30,
            ),
        ),
    ]
