upstream printbuddy_upstream {
    server 127.0.0.1:8001;
}

server {
    server_name printbuddy.datemyhobby.com;

    location /static/ {
        alias /opt/printbuddy/staticfiles/;
        expires 30d;
    }

    location /media/ {
        alias /opt/printbuddy/media/;
        expires 7d;
    }

    location /nas/ {
        alias /mnt/agency_nas/;
        expires 30d;
    }

    location / {
        proxy_pass http://printbuddy_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120;
    }

    location /shop/webhook/stripe/ {
        proxy_pass http://printbuddy_upstream;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 30;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/printbuddy.datemyhobby.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/printbuddy.datemyhobby.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = printbuddy.datemyhobby.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen 80;
    server_name printbuddy.datemyhobby.com;
    return 404; # managed by Certbot
}
