# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("file_path", models.ImageField(upload_to="gallery/full/")),
                (
                    "thumb_path",
                    models.ImageField(blank=True, upload_to="gallery/thumbs/"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("shirt", "T-Shirt"),
                            ("poster", "Poster"),
                            ("card", "Grußkarte"),
                            ("art", "Kunstdruck"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Kommasepariert", max_length=250
                    ),
                ),
                (
                    "cta_type",
                    models.CharField(
                        choices=[
                            ("etsy", "Etsy"),
                            ("shop", "Eigener Shop"),
                            ("contact", "Kontakt"),
                        ],
                        default="shop",
                        max_length=20,
                    ),
                ),
                ("cta_url", models.URLField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "source_job_id",
                    models.UUIDField(
                        blank=True, help_text="Loses Coupling — kein FK", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Galerie-Bild",
                "verbose_name_plural": "Galerie-Bilder",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
