# Generated by Django 5.1.15 on 2026-07-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial_models"),
        ("jobs", "0003_add_project_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryimage",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Projekt-Zuordnung (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_images",
                to="jobs.project",
            ),
        ),
    ]
