# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FulfillmentPartner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("contact_name", models.CharField(max_length=100)),
                (
                    "export_formats",
                    models.JSONField(default=list, help_text="['pod','cmyk','vector']"),
                ),
                ("notify_email", models.BooleanField(default=True)),
                ("notify_webhook_url", models.CharField(blank=True, max_length=500)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Fulfillment-Partner",
                "verbose_name_plural": "Fulfillment-Partner",
            },
        ),
        migrations.CreateModel(
            name="PartnerProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_types", models.JSONField(default=list)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Partner-Produkt",
                "verbose_name_plural": "Partner-Produkte",
            },
        ),
        migrations.CreateModel(
            name="PartnerVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_sku", models.CharField(blank=True, max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partners.fulfillmentpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Partner-Variante",
                "verbose_name_plural": "Partner-Varianten",
            },
        ),
    ]
