# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("partners", "0001_initial_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0001_initial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnervariant",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.productvariant"
            ),
        ),
        migrations.AddField(
            model_name="partnerproduct",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partners.fulfillmentpartner",
            ),
        ),
        migrations.AddField(
            model_name="partnerproduct",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.product"
            ),
        ),
        migrations.AddField(
            model_name="fulfillmentpartner",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partnervariant",
            unique_together={("partner", "variant")},
        ),
        migrations.AlterUniqueTogether(
            name="partnerproduct",
            unique_together={("partner", "product")},
        ),
    ]
