# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrintBundle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("asset_ids", models.JSONField(default=list)),
                ("bundle_path", models.CharField(blank=True, max_length=500)),
                (
                    "format",
                    models.CharField(
                        choices=[("zip", "ZIP-Archiv"), ("folder", "Ordner")],
                        default="zip",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("building", "Wird erstellt"),
                            ("ready", "Fertig"),
                            ("delivered", "Ausgeliefert"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Print-Bundle",
                "verbose_name_plural": "Print-Bundles",
            },
        ),
    ]
