# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bundles", "0001_initial_models"),
        ("shop", "0001_initial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="printbundle",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="shop.order"
            ),
        ),
    ]
