# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial_models"),
        ("partners", "0001_initial_models"),
        ("gallery", "0001_initial_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_session_id", models.CharField(max_length=200, unique=True)),
                ("stripe_payment_id", models.CharField(blank=True, max_length=200)),
                ("printful_order_id", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("paid", "Bezahlt"),
                            ("processing", "In Bearbeitung"),
                            ("shipped", "Versendet"),
                            ("delivered", "Geliefert"),
                            ("cancelled", "Storniert"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(max_length=100)),
                (
                    "shipping_address",
                    models.JSONField(help_text="Von Stripe-Event, nie direkt vom User"),
                ),
                ("total_eur", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tracking_code", models.CharField(blank=True, max_length=100)),
                ("source_channel", models.CharField(default="shop", max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="channels.saleschannel",
                    ),
                ),
                (
                    "fulfillment_partner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.fulfillmentpartner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellung",
                "verbose_name_plural": "Bestellungen",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("category", models.CharField(max_length=40)),
                ("base_image", models.ImageField(upload_to="shop/products/")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Produkt",
                "verbose_name_plural": "Produkte",
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.CharField(max_length=10)),
                ("color", models.CharField(max_length=40)),
                ("printful_variant_id", models.CharField(max_length=50)),
                ("price_eur", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cost_eur", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "required_export_types",
                    models.JSONField(
                        default=list, help_text="z.B. ['pod','cmyk','preview']"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produkt-Variante",
                "verbose_name_plural": "Produkt-Varianten",
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="shop.order",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shop.productvariant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bestellposition",
                "verbose_name_plural": "Bestellpositionen",
            },
        ),
        migrations.CreateModel(
            name="ImageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mockup_file",
                    models.ImageField(blank=True, upload_to="shop/mockups/"),
                ),
                (
                    "mockup_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ausstehend"),
                            ("generating", "Wird generiert"),
                            ("ready", "Fertig"),
                            ("failed", "Fehlgeschlagen"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="gallery.galleryimage",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="shop.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bild-Produkt-Zuordnung",
                "verbose_name_plural": "Bild-Produkt-Zuordnungen",
                "unique_together": {("image", "product")},
            },
        ),
    ]
