# Generated by Django 4.2.30 on 2026-06-29 21:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("own_shop", "Eigener Shop"),
                            ("etsy", "Etsy"),
                            ("woocommerce", "WooCommerce"),
                            ("shopify", "Shopify"),
                            ("manual", "Manuell"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("webhook_url", models.CharField(blank=True, max_length=500)),
                (
                    "api_key",
                    models.CharField(
                        blank=True, help_text="Verschlüsselt in DB", max_length=200
                    ),
                ),
                (
                    "api_secret",
                    models.CharField(
                        blank=True, help_text="Verschlüsselt in DB", max_length=200
                    ),
                ),
                (
                    "base_url",
                    models.URLField(
                        blank=True, help_text="Für WooCommerce, Shopify etc."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vertriebskanal",
                "verbose_name_plural": "Vertriebskanäle",
            },
        ),
    ]
